# Generated by Django 4.0.5 on 2022-06-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recom',
            fields=[
                ('keyid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rec_rank', models.IntegerField()),
                ('itemtype', models.CharField(blank=True, db_column='itemType', max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('descrptn', models.CharField(blank=True, max_length=5000, null=True)),
                ('datemod', models.DateTimeField(db_column='dateMod')),
                ('urllink', models.CharField(max_length=2000)),
                ('tags', models.CharField(blank=True, max_length=1000, null=True)),
                ('bookmarkflag', models.IntegerField()),
                ('views', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recom',
                'managed': False,
            },
        ),
    ]
